import math
from src.core.dependencies.uow import UnitOfWork
from src.exceptions.general_exceptions import CannotUpdate
from src.exceptions.transaction_exceptions import TransactionAutoGenerated, TransactionCancelled, TransactionNotFound
from src.schemas.base import RequestAllObject
from src.repository.transaction.transaction_model import Transaction
from src.schemas.transaction.create import TransactionCreateSchema
from src.schemas.transaction.update import TransactionUpdateSchema

class TransactionService():
    def __init__(self, uow: UnitOfWork):
        self.uow = uow

    async def create(self, data: TransactionCreateSchema) -> Transaction:
        transactionData = data.model_dump()
        newTransaction = Transaction(**transactionData)
        return await self.uow.transactions.create(newTransaction)
    
    async def update(self, data: TransactionUpdateSchema) -> Transaction:
        checkIfExists = await self.uow.transactions.get(data.id)
        if checkIfExists is None: raise TransactionNotFound(data.id)
        if checkIfExists.auto_generated: raise TransactionAutoGenerated(data.id)

        dataDict = data.model_dump(exclude = {"id"}, exclude_unset = True)
        result = await self.uow.transactions.update(data.id, **dataDict)
        if result is None: raise CannotUpdate(data.id, "transactions")
        return result
    
    async def get(self, id: int) -> Transaction:
        result = await self.uow.transactions.get(id)
        if result is None: raise TransactionNotFound(id)
        return result
    
    async def get_many(self, ids: list[int]) -> list[Transaction]:
        return await self.uow.transactions.get_by_ids(ids)
    
    async def get_all(self, data: RequestAllObject) -> dict:
        items, total_items = await self.uow.transactions.get_all(data)

        total_pages = math.ceil(total_items / data.pageSize) if data.pageSize > 0 else 0
        
        return {
            "items": items,
            "page": data.page,
            "pageSize": data.pageSize,
            "totalItems": total_items,
            "totalPages": total_pages
        }
    
    async def cancel(self, id: int) -> Transaction:
        transaction = await self.uow.transactions.get(id)
        if transaction is None: raise TransactionNotFound(id)
        if transaction.cancelled: raise TransactionCancelled(id)
        if transaction.auto_generated: raise TransactionAutoGenerated(id)

        result = await self.uow.transactions.update(id, cancelled = True)
        if result is None: raise CannotUpdate(id, "transactions")
        return result