import math
from src.core.dependencies.uow import UnitOfWork
from src.exceptions.general_exceptions import CannotUpdate
from src.exceptions.transaction_exceptions import TransactionAutoGenerated, TransactionCancelled, TransactionNotFound
from src.schemas.analytics.request import GetReportWithFilters
from src.schemas.analytics.transationResponse import TransactionAnalyticsResponse
from src.schemas.base import RequestAllObject
from src.repository.transaction.transaction_model import Transaction, TransactionMethod
from src.schemas.transaction.create import TransactionCreateSchema
from src.schemas.transaction.update import TransactionUpdateSchema

class TransactionService():
    def __init__(self, uow: UnitOfWork):
        self.uow = uow

    async def create(self, data: TransactionCreateSchema) -> Transaction:
        transactionData = data.model_dump()
        newTransaction = Transaction(**transactionData)
        return await self.uow.transactions.create(newTransaction)
    
    async def update(self, data: TransactionUpdateSchema) -> Transaction:
        checkIfExists = await self.uow.transactions.get(data.id)
        if checkIfExists is None: raise TransactionNotFound(data.id)
        if checkIfExists.auto_generated: raise TransactionAutoGenerated(data.id)

        dataDict = data.model_dump(exclude = {"id"}, exclude_unset = True)
        result = await self.uow.transactions.update(data.id, **dataDict)
        if result is None: raise CannotUpdate(data.id, "transactions")
        return result
    
    async def get(self, id: int) -> Transaction:
        result = await self.uow.transactions.get(id)
        if result is None: raise TransactionNotFound(id)
        return result
    
    async def get_many(self, ids: list[int]) -> list[Transaction]:
        return await self.uow.transactions.get_by_ids(ids)
    
    async def get_all(self, data: RequestAllObject) -> dict:
        items, total_items = await self.uow.transactions.get_all(data)

        total_pages = math.ceil(total_items / data.pageSize) if data.pageSize > 0 else 0
        
        return {
            "items": items,
            "page": data.page,
            "pageSize": data.pageSize,
            "totalItems": total_items,
            "totalPages": total_pages
        }
    
    async def cancel(self, id: int) -> Transaction:
        transaction = await self.uow.transactions.get(id)
        if transaction is None: raise TransactionNotFound(id)
        if transaction.cancelled: raise TransactionCancelled(id)
        if transaction.auto_generated: raise TransactionAutoGenerated(id)

        result = await self.uow.transactions.update(id, cancelled = True)
        if result is None: raise CannotUpdate(id, "transactions")
        return result

    async def get_analytics(self, data: GetReportWithFilters) -> TransactionAnalyticsResponse:
        transactions = await self.uow.transactions.get_analytics(data)
        if len(transactions) == 0: return

        result = {
            "payment_methods": {
                "cash": {
                    "amount": 0,
                    "profit": 0,
                    "percentage": 0
                },
                "card": {
                    "amount": 0,
                    "profit": 0,
                    "percentage": 0
                },
                "deposit": {
                    "amount": 0,
                    "profit": 0,
                    "percentage": 0
                },
                "gift_card": {
                    "amount": 0,
                    "profit": 0,
                    "percentage": 0
                },
                "bank_transfer": {
                    "amount": 0,
                    "profit": 0,
                    "percentage": 0
                }
            },
            "by_service": {
                "amount": 0,
                "profit": 0,
                "percentage": 0,
            },
            "by_material": {
                "amount": 0,
                "profit": 0,
                "percentage": 0,
            },
            "by_giftCard": {
                "amount": 0,
                "profit": 0,
                "percentage": 0,
            },
            "not_fully_paid_receipts_sum": 0,
            "total_profit": 0,
        }

        result["total_profit"] = sum([transation.amount for transation in transactions])
        key: str

        for transaction in transactions:
            match transaction.method:
                case TransactionMethod.CASH: key = "cash"
                case TransactionMethod.CARD: key = "card"
                case TransactionMethod.DEPOSIT: key = "deposit"
                case TransactionMethod.GIFT_CARD: key = "gift_card"
                case TransactionMethod.BANK_TRANSFER: key = "bank_transfer"
                case _: continue 

            result["payment_methods"][key]["amount"] += 1
            result["payment_methods"][key]["profit"] += transaction.amount

            if transaction.receipt_id:
                receiptItems = transaction.receipt.items
                for item in receiptItems:
                    if item.material_id:
                        result["by_material"]["amount"] += 1
                        result["by_material"]["profit"] += transaction.amount
                    elif item.giftCard_id:
                        result["by_giftCard"]["amount"] += 1
                        result["by_giftCard"]["profit"] += transaction.amount
                    elif item.appointment_service and transaction.receipt.remaining_amount == 0:
                        if item.appointment_service.material_id:
                            materialPrice = item.appointment_service.final_price
                            result["by_material"]["amount"] += 1
                            result["by_material"]["profit"] += materialPrice
                        if item.appointment_service.service_id:
                            servicePrice = item.appointment_service.final_price
                            result["by_service"]["amount"] += 1
                            result["by_service"]["profit"] += servicePrice
                    elif item.appointment_service and transaction.receipt.remaining_amount >= 1:
                        result["not_fully_paid_receipts_sum"] += transaction.amount

        totalProfit = result["total_profit"]
        for methodData in result["payment_methods"].values():
            methodData["percentage"] = (
                round(methodData["profit"] / totalProfit * 100, 2) if totalProfit else 0
            )

        for category in ("by_service", "by_material", "by_giftCard"):
            result[category]["percentage"] = (
                round(result[category]["profit"] / totalProfit * 100, 2) if totalProfit else 0
            )

        return TransactionAnalyticsResponse.model_validate(result)