"""empty message

Revision ID: 052db73ad7e4
Revises: cf73643336f9
Create Date: 2026-07-30 22:02:21.739243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '052db73ad7e4'
down_revision: Union[str, Sequence[str], None] = 'cf73643336f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_users', sa.Column('active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_users', 'active')
    # ### end Alembic commands ###
