"""add tenant parent_id for branches

Revision ID: 0d25cbf1ec1e
Revises: 3697209de113
Create Date: 2026-08-18 18:13:37.686746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d25cbf1ec1e'
down_revision: Union[str, Sequence[str], None] = '3697209de113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tenants_parent_id'), 'tenants', ['parent_id'], unique=False)
    op.create_foreign_key('fk_tenants_parent_id_tenants', 'tenants', 'tenants', ['parent_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tenants_parent_id_tenants', 'tenants', type_='foreignkey')
    op.drop_index(op.f('ix_tenants_parent_id'), table_name='tenants')
    op.drop_column('tenants', 'parent_id')
    # ### end Alembic commands ###
