"""promotion_table

Revision ID: 3925775c3389
Revises: 72895aaf3d9e
Create Date: 2026-08-10 14:36:42.014444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3925775c3389'
down_revision: Union[str, Sequence[str], None] = '72895aaf3d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('promo_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_value', sa.Numeric(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_actor_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'tenant_id', name='uq_promotion_name_tenant')
    )
    op.create_index(op.f('ix_promotions_tenant_id'), 'promotions', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('uq_employee_per_tenant'), 'employees', type_='unique')
    op.drop_constraint(op.f('materials_article_key'), 'materials', type_='unique')
    op.create_unique_constraint('uq_material_article', 'materials', ['article', 'tenant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_material_article', 'materials', type_='unique')
    op.create_unique_constraint(op.f('materials_article_key'), 'materials', ['article'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_employee_per_tenant'), 'employees', ['phone', 'tenant_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_promotions_tenant_id'), table_name='promotions')
    op.drop_table('promotions')
    # ### end Alembic commands ###
