"""empty message

Revision ID: 3928bd3f0961
Revises: 2eadef85b5f7
Create Date: 2026-07-16 14:13:00.578059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3928bd3f0961'
down_revision: Union[str, Sequence[str], None] = '2eadef85b5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('estimated_time', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'estimated_time')
    # ### end Alembic commands ###
