"""empty message

Revision ID: 4634859a0ebe
Revises: a0e4c12675ee
Create Date: 2026-08-17 15:45:47.203398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4634859a0ebe'
down_revision: Union[str, Sequence[str], None] = 'a0e4c12675ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift_cards', sa.Column('cancelled_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gift_cards', 'cancelled_reason')
    # ### end Alembic commands ###
