"""empty message

Revision ID: 56fa4630ba70
Revises: 4e51960ae83e
Create Date: 2026-08-13 12:43:37.723105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56fa4630ba70'
down_revision: Union[str, Sequence[str], None] = '4e51960ae83e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_cards',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('initial_amount', sa.Integer(), nullable=False),
    sa.Column('remain_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_actor_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('initial_amount >= 1', name='cc_initial_amount_positive'),
    sa.ForeignKeyConstraint(['client_id', 'tenant_id'], ['clients.id', 'clients.tenant_id'], name='fk_gift_card_client', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receipt_id', 'tenant_id'], ['receipts.id', 'receipts.tenant_id'], name='fk_gift_card_receipt', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_gift_card_tenant')
    )
    op.create_index(op.f('ix_gift_cards_tenant_id'), 'gift_cards', ['tenant_id'], unique=False)
    op.create_index('uq_gift_card_code', 'gift_cards', [sa.literal_column('lower(code)')], unique=True)
    op.add_column('receipt_items', sa.Column('giftCard_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_gift_card_item_receipt', 'receipt_items', 'gift_cards', ['giftCard_id', 'tenant_id'], ['id', 'tenant_id'], ondelete='SET NULL')
    op.drop_constraint('chk_receipt_item_exclusive_source', 'receipt_items', type_='check')
    op.create_check_constraint(
        'chk_receipt_item_exclusive_source',
        'receipt_items',
        '(material_id IS NOT NULL AND appointment_service_id IS NULL AND "giftCard_id" IS NULL) OR '
        '(material_id IS NULL AND appointment_service_id IS NOT NULL AND "giftCard_id" IS NULL) OR '
        '(material_id IS NULL AND appointment_service_id IS NULL AND "giftCard_id" IS NOT NULL)'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_receipt_item_exclusive_source', 'receipt_items', type_='check')
    op.create_check_constraint(
        'chk_receipt_item_exclusive_source',
        'receipt_items',
        '(material_id IS NOT NULL AND appointment_service_id IS NULL) OR '
        '(material_id IS NULL AND appointment_service_id IS NOT NULL)'
    )
    op.drop_constraint('fk_gift_card_item_receipt', 'receipt_items', type_='foreignkey')
    op.drop_column('receipt_items', 'giftCard_id')
    op.drop_index('uq_gift_card_code', table_name='gift_cards')
    op.drop_index(op.f('ix_gift_cards_tenant_id'), table_name='gift_cards')
    op.drop_table('gift_cards')
    # ### end Alembic commands ###
