"""empty message

Revision ID: 6bfd3ca78feb
Revises: 3791824ca58c
Create Date: 2026-08-11 13:45:13.383004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bfd3ca78feb'
down_revision: Union[str, Sequence[str], None] = '3791824ca58c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_receipt_item_promotion'), 'receipt_items', type_='foreignkey')
    op.drop_column('receipt_items', 'promotion_id')
    op.drop_constraint(op.f('fk_receipt_promotion'), 'receipts', type_='foreignkey')
    op.drop_column('receipts', 'promotion_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('promotion_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_receipt_promotion'), 'receipts', 'promotions', ['promotion_id', 'tenant_id'], ['id', 'tenant_id'], ondelete='SET NULL')
    op.add_column('receipt_items', sa.Column('promotion_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_receipt_item_promotion'), 'receipt_items', 'promotions', ['promotion_id', 'tenant_id'], ['id', 'tenant_id'], ondelete='SET NULL')
    # ### end Alembic commands ###
