"""empty message

Revision ID: 8020aa684129
Revises: c6dfd2b53d6e
Create Date: 2026-09-21 23:46:37.754530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8020aa684129'
down_revision: Union[str, Sequence[str], None] = 'c6dfd2b53d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('tenant_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('amount', sa.Numeric(precision=30, scale=2), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expense_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('tenant_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('amount', sa.Numeric(precision=30, scale=2), nullable=False),
    sa.Column('gateway', sa.String(length=255), nullable=True),
    sa.Column('gateway_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway', 'gateway_transaction_id', name='uq_tenant_payments_gateway_transaction')
    )
    op.create_table('tenant_addons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('limit_key', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['tenant_expenses.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('subscription_plans', sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('subscription_plans', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('subscription_plans', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('subscription_plans', 'max_archive_period')
    op.add_column('tenant_subscriptions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('tenant_subscriptions', 'billing_interval')
    op.add_column('tenants', sa.Column('balance', sa.Numeric(precision=30, scale=2), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'balance')
    op.add_column('tenant_subscriptions', sa.Column('billing_interval', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tenant_subscriptions', 'created_at')
    op.add_column('subscription_plans', sa.Column('max_archive_period', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('subscription_plans', 'updated_at')
    op.drop_column('subscription_plans', 'created_at')
    op.drop_column('subscription_plans', 'archived')
    op.drop_table('tenant_addons')
    op.drop_table('tenant_payments')
    op.drop_table('tenant_expenses')
    # ### end Alembic commands ###
