"""empty message

Revision ID: c6dfd2b53d6e
Revises: 6315285aedc0
Create Date: 2026-09-20 00:08:35.485242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6dfd2b53d6e'
down_revision: Union[str, Sequence[str], None] = '6315285aedc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promotions', 'discount_value',
               existing_type=sa.NUMERIC(precision=30, scale=2),
               nullable=False)
    op.add_column('subscription_plans', sa.Column('max_branches', sa.Integer(), nullable=True))
    op.add_column('subscription_plans', sa.Column('max_users', sa.Integer(), nullable=True))
    op.alter_column('subscription_plans', 'max_clients',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscription_plans', 'max_archive_period',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('subscription_plans', 'max_materials')
    op.drop_column('subscription_plans', 'max_employees')
    op.drop_column('subscription_plans', 'max_services')
    op.create_unique_constraint(None, 'tenant_subscriptions', ['tenant_id'])
    op.drop_constraint(op.f('tenant_subscriptions_plan_id_fkey'), 'tenant_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_subscriptions', 'subscription_plans', ['plan_id'], ['id'], ondelete='restrict')
    op.drop_column('tenant_subscriptions', 'cancel_at_period_end')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_subscriptions', sa.Column('cancel_at_period_end', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tenant_subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('tenant_subscriptions_plan_id_fkey'), 'tenant_subscriptions', 'subscription_plans', ['plan_id'], ['id'])
    op.drop_constraint(None, 'tenant_subscriptions', type_='unique')
    op.add_column('subscription_plans', sa.Column('max_services', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('subscription_plans', sa.Column('max_employees', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('subscription_plans', sa.Column('max_materials', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('subscription_plans', 'max_archive_period',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscription_plans', 'max_clients',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('subscription_plans', 'max_users')
    op.drop_column('subscription_plans', 'max_branches')
    op.alter_column('promotions', 'discount_value',
               existing_type=sa.NUMERIC(precision=30, scale=2),
               nullable=True)
    # ### end Alembic commands ###
