"""empty message

Revision ID: d0386f2e44b4
Revises: b45b6e1c2a0a
Create Date: 2026-08-17 14:38:18.244290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0386f2e44b4'
down_revision: Union[str, Sequence[str], None] = 'b45b6e1c2a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'notes')
    # ### end Alembic commands ###
