"""discount_nullable

Revision ID: d26add1849ed
Revises: 3925775c3389
Create Date: 2026-08-10 14:53:34.118111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd26add1849ed'
down_revision: Union[str, Sequence[str], None] = '3925775c3389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promotions', 'discount_value',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promotions', 'discount_value',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###
