from .base import BaseAppException

class TransactionNotFound(BaseAppException):
    statusCode = 404
    errorCode = "TRANSACTION_NOT_FOUND"
    def __init__(self, id: int):
        super().__init__(
            detail=f"Transaction ID {id} not found",
            errorCode = self.errorCode,
            id = id
        )

class TransactionCancelled(BaseAppException):
    statusCode = 409
    errorCode = "TRANSACTION_IS_CANCELLED"
    def __init__(self, id: int):
        super().__init__(
            detail = f"Transcation ID {id} not found",
            errorCode = self.errorCode,
            id = id
        )

class TransactionAutoGenerated(BaseAppException):
    statusCode = 409
    errorCode = "TRANSACTION_IS_AUTO_GENERATED"
    def __init__(self, id: int):
        super().__init__(
            detail = f"This transaction (ID {id}) auto generated, changes cannot be applied manually.",
            errorCode = self.errorCode,
            id = id
        )